# Generated by Django 5.1.4 on 2025-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
